### ISSUE TITLE
As an Unauthenticated User - 10

### ISSUE THREAD

**Issue by Dmitry1007** [kravinskylev/dinner_dash#10]
When I visit the new user page ‘/user/new'
I fill out a form with my Username, and Password
And click on ‘Create New User’
I’m re-directed to my show page
And I expect to see my username

**Comment by RickBacci** [comment]
double check registration for email and name

**Comment by RickBacci** [comment]
redirect to root_path

**Comment by RickBacci** [comment]
categories/index
